# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_collector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet_collector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16packet_collector.proto\"\"\n\rNetFilterInfo\x12\x11\n\thookpoint\x18\x01 \x01(\t\"\x1d\n\x08\x65\x42PFInfo\x12\x11\n\thookpoint\x18\x01 \x01(\t\"\xb3\x01\n\nPacketInfo\x12\x10\n\x06packet\x18\x01 \x01(\x0cH\x00\x12\x13\n\tpacket_id\x18\x02 \x01(\x04H\x00\x12\x0f\n\x07node_id\x18\x05 \x01(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\x01\x12\'\n\rnetfilterInfo\x18\n \x01(\x0b\x32\x0e.NetFilterInfoH\x01\x12\x1d\n\x08\x65\x62pfInfo\x18\x0b \x01(\x0b\x32\t.eBPFInfoH\x01\x42\x06\n\x04\x64\x61taB\n\n\x08metadata\"U\n\x12PollSettingRequest\x12\x0f\n\x07node_id\x18\x02 \x01(\r\x12\x16\n\x0enode_id_length\x18\x03 \x01(\r\x12\x16\n\x0e\x63ounter_length\x18\x04 \x01(\r\"\x12\n\x10PollSettingReply\"\x13\n\x11PacketInfoRequest\"4\n\x0fPacketInfoReply\x12!\n\x0cpacket_infos\x18\x01 \x03(\x0b\x32\x0b.PacketInfo\"\x94\x01\n\x17PacketInfoStreamRequest\x12 \n\x13\x63\x61pture_all_packets\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x0f\n\x07node_id\x18\x02 \x01(\r\x12\x16\n\x0enode_id_length\x18\x03 \x01(\r\x12\x16\n\x0e\x63ounter_length\x18\x04 \x01(\rB\x16\n\x14_capture_all_packets*:\n\x0b\x43ollectMode\x12\x10\n\x0cUNKNOWN_MODE\x10\x00\x12\n\n\x06PACKET\x10\x01\x12\r\n\tPACKET_ID\x10\x02\x32\xc6\x01\n\x14PacketCollectService\x12\x33\n\x07SetPoll\x12\x13.PollSettingRequest\x1a\x11.PollSettingReply\"\x00\x12\x37\n\rGetPacketInfo\x12\x12.PacketInfoRequest\x1a\x10.PacketInfoReply\"\x00\x12@\n\x13GetPacketInfoStream\x12\x18.PacketInfoStreamRequest\x1a\x0b.PacketInfo\"\x00\x30\x01\x62\x06proto3'
)

_COLLECTMODE = _descriptor.EnumDescriptor(
  name='CollectMode',
  full_name='CollectMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_MODE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PACKET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PACKET_ID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=608,
  serialized_end=666,
)
_sym_db.RegisterEnumDescriptor(_COLLECTMODE)

CollectMode = enum_type_wrapper.EnumTypeWrapper(_COLLECTMODE)
UNKNOWN_MODE = 0
PACKET = 1
PACKET_ID = 2



_NETFILTERINFO = _descriptor.Descriptor(
  name='NetFilterInfo',
  full_name='NetFilterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hookpoint', full_name='NetFilterInfo.hookpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_EBPFINFO = _descriptor.Descriptor(
  name='eBPFInfo',
  full_name='eBPFInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hookpoint', full_name='eBPFInfo.hookpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)


_PACKETINFO = _descriptor.Descriptor(
  name='PacketInfo',
  full_name='PacketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='PacketInfo.packet', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_id', full_name='PacketInfo.packet_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='PacketInfo.node_id', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PacketInfo.timestamp', index=3,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='netfilterInfo', full_name='PacketInfo.netfilterInfo', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ebpfInfo', full_name='PacketInfo.ebpfInfo', index=5,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='PacketInfo.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='metadata', full_name='PacketInfo.metadata',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=94,
  serialized_end=273,
)


_POLLSETTINGREQUEST = _descriptor.Descriptor(
  name='PollSettingRequest',
  full_name='PollSettingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='PollSettingRequest.node_id', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id_length', full_name='PollSettingRequest.node_id_length', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_length', full_name='PollSettingRequest.counter_length', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=360,
)


_POLLSETTINGREPLY = _descriptor.Descriptor(
  name='PollSettingReply',
  full_name='PollSettingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=380,
)


_PACKETINFOREQUEST = _descriptor.Descriptor(
  name='PacketInfoRequest',
  full_name='PacketInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=401,
)


_PACKETINFOREPLY = _descriptor.Descriptor(
  name='PacketInfoReply',
  full_name='PacketInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_infos', full_name='PacketInfoReply.packet_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=455,
)


_PACKETINFOSTREAMREQUEST = _descriptor.Descriptor(
  name='PacketInfoStreamRequest',
  full_name='PacketInfoStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_all_packets', full_name='PacketInfoStreamRequest.capture_all_packets', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='PacketInfoStreamRequest.node_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id_length', full_name='PacketInfoStreamRequest.node_id_length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_length', full_name='PacketInfoStreamRequest.counter_length', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_capture_all_packets', full_name='PacketInfoStreamRequest._capture_all_packets',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=458,
  serialized_end=606,
)

_PACKETINFO.fields_by_name['netfilterInfo'].message_type = _NETFILTERINFO
_PACKETINFO.fields_by_name['ebpfInfo'].message_type = _EBPFINFO
_PACKETINFO.oneofs_by_name['data'].fields.append(
  _PACKETINFO.fields_by_name['packet'])
_PACKETINFO.fields_by_name['packet'].containing_oneof = _PACKETINFO.oneofs_by_name['data']
_PACKETINFO.oneofs_by_name['data'].fields.append(
  _PACKETINFO.fields_by_name['packet_id'])
_PACKETINFO.fields_by_name['packet_id'].containing_oneof = _PACKETINFO.oneofs_by_name['data']
_PACKETINFO.oneofs_by_name['metadata'].fields.append(
  _PACKETINFO.fields_by_name['netfilterInfo'])
_PACKETINFO.fields_by_name['netfilterInfo'].containing_oneof = _PACKETINFO.oneofs_by_name['metadata']
_PACKETINFO.oneofs_by_name['metadata'].fields.append(
  _PACKETINFO.fields_by_name['ebpfInfo'])
_PACKETINFO.fields_by_name['ebpfInfo'].containing_oneof = _PACKETINFO.oneofs_by_name['metadata']
_PACKETINFOREPLY.fields_by_name['packet_infos'].message_type = _PACKETINFO
_PACKETINFOSTREAMREQUEST.oneofs_by_name['_capture_all_packets'].fields.append(
  _PACKETINFOSTREAMREQUEST.fields_by_name['capture_all_packets'])
_PACKETINFOSTREAMREQUEST.fields_by_name['capture_all_packets'].containing_oneof = _PACKETINFOSTREAMREQUEST.oneofs_by_name['_capture_all_packets']
DESCRIPTOR.message_types_by_name['NetFilterInfo'] = _NETFILTERINFO
DESCRIPTOR.message_types_by_name['eBPFInfo'] = _EBPFINFO
DESCRIPTOR.message_types_by_name['PacketInfo'] = _PACKETINFO
DESCRIPTOR.message_types_by_name['PollSettingRequest'] = _POLLSETTINGREQUEST
DESCRIPTOR.message_types_by_name['PollSettingReply'] = _POLLSETTINGREPLY
DESCRIPTOR.message_types_by_name['PacketInfoRequest'] = _PACKETINFOREQUEST
DESCRIPTOR.message_types_by_name['PacketInfoReply'] = _PACKETINFOREPLY
DESCRIPTOR.message_types_by_name['PacketInfoStreamRequest'] = _PACKETINFOSTREAMREQUEST
DESCRIPTOR.enum_types_by_name['CollectMode'] = _COLLECTMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetFilterInfo = _reflection.GeneratedProtocolMessageType('NetFilterInfo', (_message.Message,), {
  'DESCRIPTOR' : _NETFILTERINFO,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:NetFilterInfo)
  })
_sym_db.RegisterMessage(NetFilterInfo)

eBPFInfo = _reflection.GeneratedProtocolMessageType('eBPFInfo', (_message.Message,), {
  'DESCRIPTOR' : _EBPFINFO,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:eBPFInfo)
  })
_sym_db.RegisterMessage(eBPFInfo)

PacketInfo = _reflection.GeneratedProtocolMessageType('PacketInfo', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFO,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfo)
  })
_sym_db.RegisterMessage(PacketInfo)

PollSettingRequest = _reflection.GeneratedProtocolMessageType('PollSettingRequest', (_message.Message,), {
  'DESCRIPTOR' : _POLLSETTINGREQUEST,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PollSettingRequest)
  })
_sym_db.RegisterMessage(PollSettingRequest)

PollSettingReply = _reflection.GeneratedProtocolMessageType('PollSettingReply', (_message.Message,), {
  'DESCRIPTOR' : _POLLSETTINGREPLY,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PollSettingReply)
  })
_sym_db.RegisterMessage(PollSettingReply)

PacketInfoRequest = _reflection.GeneratedProtocolMessageType('PacketInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFOREQUEST,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfoRequest)
  })
_sym_db.RegisterMessage(PacketInfoRequest)

PacketInfoReply = _reflection.GeneratedProtocolMessageType('PacketInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFOREPLY,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfoReply)
  })
_sym_db.RegisterMessage(PacketInfoReply)

PacketInfoStreamRequest = _reflection.GeneratedProtocolMessageType('PacketInfoStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFOSTREAMREQUEST,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfoStreamRequest)
  })
_sym_db.RegisterMessage(PacketInfoStreamRequest)



_PACKETCOLLECTSERVICE = _descriptor.ServiceDescriptor(
  name='PacketCollectService',
  full_name='PacketCollectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=669,
  serialized_end=867,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetPoll',
    full_name='PacketCollectService.SetPoll',
    index=0,
    containing_service=None,
    input_type=_POLLSETTINGREQUEST,
    output_type=_POLLSETTINGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPacketInfo',
    full_name='PacketCollectService.GetPacketInfo',
    index=1,
    containing_service=None,
    input_type=_PACKETINFOREQUEST,
    output_type=_PACKETINFOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPacketInfoStream',
    full_name='PacketCollectService.GetPacketInfoStream',
    index=2,
    containing_service=None,
    input_type=_PACKETINFOSTREAMREQUEST,
    output_type=_PACKETINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PACKETCOLLECTSERVICE)

DESCRIPTOR.services_by_name['PacketCollectService'] = _PACKETCOLLECTSERVICE

# @@protoc_insertion_point(module_scope)
