# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_collector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16packet_collector.proto\"\"\n\rNetFilterInfo\x12\x11\n\thookpoint\x18\x01 \x01(\t\"(\n\x08\x45\x42PFInfo\x12\x1c\n\thookpoint\x18\x01 \x01(\x0e\x32\t.EBPFHook\"\xb3\x01\n\nPacketInfo\x12\x10\n\x06packet\x18\x01 \x01(\x0cH\x00\x12\x13\n\tpacket_id\x18\x02 \x01(\x04H\x00\x12\x0f\n\x07node_id\x18\x05 \x01(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\x01\x12\'\n\rnetfilterInfo\x18\n \x01(\x0b\x32\x0e.NetFilterInfoH\x01\x12\x1d\n\x08\x65\x62pfInfo\x18\x0b \x01(\x0b\x32\t.EBPFInfoH\x01\x42\x06\n\x04\x64\x61taB\n\n\x08metadata\"U\n\x12PollSettingRequest\x12\x0f\n\x07node_id\x18\x02 \x01(\r\x12\x16\n\x0enode_id_length\x18\x03 \x01(\r\x12\x16\n\x0e\x63ounter_length\x18\x04 \x01(\r\"\x12\n\x10PollSettingReply\"\x13\n\x11PacketInfoRequest\"4\n\x0fPacketInfoReply\x12!\n\x0cpacket_infos\x18\x01 \x03(\x0b\x32\x0b.PacketInfo\"w\n\x17PacketInfoStreamRequest\x12\x1b\n\x13\x63\x61pture_all_packets\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\r\x12\x16\n\x0enode_id_length\x18\x03 \x01(\r\x12\x16\n\x0e\x63ounter_length\x18\x04 \x01(\r*:\n\x0b\x43ollectMode\x12\x10\n\x0cUNKNOWN_MODE\x10\x00\x12\n\n\x06PACKET\x10\x01\x12\r\n\tPACKET_ID\x10\x02*D\n\x08\x45\x42PFHook\x12\x10\n\x0cUNKNOWN_HOOK\x10\x00\x12\x07\n\x03XDP\x10\x01\x12\x0e\n\nTC_INGRESS\x10\x02\x12\r\n\tTC_EGRESS\x10\x03\x32\xc6\x01\n\x14PacketCollectService\x12\x33\n\x07SetPoll\x12\x13.PollSettingRequest\x1a\x11.PollSettingReply\"\x00\x12\x37\n\rGetPacketInfo\x12\x12.PacketInfoRequest\x1a\x10.PacketInfoReply\"\x00\x12@\n\x13GetPacketInfoStream\x12\x18.PacketInfoStreamRequest\x1a\x0b.PacketInfo\"\x00\x30\x01\x42\x0bZ\t./pkg/apib\x06proto3')

_COLLECTMODE = DESCRIPTOR.enum_types_by_name['CollectMode']
CollectMode = enum_type_wrapper.EnumTypeWrapper(_COLLECTMODE)
_EBPFHOOK = DESCRIPTOR.enum_types_by_name['EBPFHook']
EBPFHook = enum_type_wrapper.EnumTypeWrapper(_EBPFHOOK)
UNKNOWN_MODE = 0
PACKET = 1
PACKET_ID = 2
UNKNOWN_HOOK = 0
XDP = 1
TC_INGRESS = 2
TC_EGRESS = 3


_NETFILTERINFO = DESCRIPTOR.message_types_by_name['NetFilterInfo']
_EBPFINFO = DESCRIPTOR.message_types_by_name['EBPFInfo']
_PACKETINFO = DESCRIPTOR.message_types_by_name['PacketInfo']
_POLLSETTINGREQUEST = DESCRIPTOR.message_types_by_name['PollSettingRequest']
_POLLSETTINGREPLY = DESCRIPTOR.message_types_by_name['PollSettingReply']
_PACKETINFOREQUEST = DESCRIPTOR.message_types_by_name['PacketInfoRequest']
_PACKETINFOREPLY = DESCRIPTOR.message_types_by_name['PacketInfoReply']
_PACKETINFOSTREAMREQUEST = DESCRIPTOR.message_types_by_name['PacketInfoStreamRequest']
NetFilterInfo = _reflection.GeneratedProtocolMessageType('NetFilterInfo', (_message.Message,), {
  'DESCRIPTOR' : _NETFILTERINFO,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:NetFilterInfo)
  })
_sym_db.RegisterMessage(NetFilterInfo)

EBPFInfo = _reflection.GeneratedProtocolMessageType('EBPFInfo', (_message.Message,), {
  'DESCRIPTOR' : _EBPFINFO,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:EBPFInfo)
  })
_sym_db.RegisterMessage(EBPFInfo)

PacketInfo = _reflection.GeneratedProtocolMessageType('PacketInfo', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFO,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfo)
  })
_sym_db.RegisterMessage(PacketInfo)

PollSettingRequest = _reflection.GeneratedProtocolMessageType('PollSettingRequest', (_message.Message,), {
  'DESCRIPTOR' : _POLLSETTINGREQUEST,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PollSettingRequest)
  })
_sym_db.RegisterMessage(PollSettingRequest)

PollSettingReply = _reflection.GeneratedProtocolMessageType('PollSettingReply', (_message.Message,), {
  'DESCRIPTOR' : _POLLSETTINGREPLY,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PollSettingReply)
  })
_sym_db.RegisterMessage(PollSettingReply)

PacketInfoRequest = _reflection.GeneratedProtocolMessageType('PacketInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFOREQUEST,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfoRequest)
  })
_sym_db.RegisterMessage(PacketInfoRequest)

PacketInfoReply = _reflection.GeneratedProtocolMessageType('PacketInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFOREPLY,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfoReply)
  })
_sym_db.RegisterMessage(PacketInfoReply)

PacketInfoStreamRequest = _reflection.GeneratedProtocolMessageType('PacketInfoStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFOSTREAMREQUEST,
  '__module__' : 'packet_collector_pb2'
  # @@protoc_insertion_point(class_scope:PacketInfoStreamRequest)
  })
_sym_db.RegisterMessage(PacketInfoStreamRequest)

_PACKETCOLLECTSERVICE = DESCRIPTOR.services_by_name['PacketCollectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t./pkg/api'
  _COLLECTMODE._serialized_start=589
  _COLLECTMODE._serialized_end=647
  _EBPFHOOK._serialized_start=649
  _EBPFHOOK._serialized_end=717
  _NETFILTERINFO._serialized_start=26
  _NETFILTERINFO._serialized_end=60
  _EBPFINFO._serialized_start=62
  _EBPFINFO._serialized_end=102
  _PACKETINFO._serialized_start=105
  _PACKETINFO._serialized_end=284
  _POLLSETTINGREQUEST._serialized_start=286
  _POLLSETTINGREQUEST._serialized_end=371
  _POLLSETTINGREPLY._serialized_start=373
  _POLLSETTINGREPLY._serialized_end=391
  _PACKETINFOREQUEST._serialized_start=393
  _PACKETINFOREQUEST._serialized_end=412
  _PACKETINFOREPLY._serialized_start=414
  _PACKETINFOREPLY._serialized_end=466
  _PACKETINFOSTREAMREQUEST._serialized_start=468
  _PACKETINFOSTREAMREQUEST._serialized_end=587
  _PACKETCOLLECTSERVICE._serialized_start=720
  _PACKETCOLLECTSERVICE._serialized_end=918
# @@protoc_insertion_point(module_scope)
